DROP database customer_shopping;
create database customer_shopping;
use customer_shopping;

select * from customer limit 20;

-- Q1. what is the total revenue generated by male vs female customers ? --
select gender , SUM(purchase_amount) as revenue
from customer
group by gender ;

-- Q2. which customer used a discount but still spent more than the average purchase amount ? --
select customer_id , purchase_amount
from customer
where discount_applied = 'yes' and purchase_amount >= (select AVG(purchase_amount)  
from customer);

-- Q3. which are the top 5 prodcuts with the heighest average review rating ? --
select item_purchased , ROUND(AVG(review_rating),2) as "Average Product Rating"
from customer
group by item_purchased
order by AVG(review_rating) DESC
limit 5; 

-- Q4. comapre the average Purchase Amounts between Standard and Express shipping
select shipping_type,
ROUND(AVG(purchase_amount),2)
from customer
Where shipping_type in('Standard', 'Express')
group by shipping_type;

-- Q5. Do subscribed customers spend more ? compare average spend and total revenue B/W subscribers and non-subscribers.->
select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
GROUP BY subscription_status
ORDER BY total_revenue , avg_spend  DESC ;

-- Q6. which 5 products have the heighest percentage of purchases with discounts applied ?
select item_purchased,
ROUND(SUM(CASE WHEN discount_applied = 'yes' THEN 1 ELSE 0 END)/COUNT(*)*100,2) as discount_rate
from customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
limit 5;

-- Q7: segment customers into New, Returning, and Loyal based on there
-- Total No of Previous Purchases, and show the count of each segment -- 
with customer_type as (
select customer_id, previous_purchases,
CASE
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 and 10 THEN 'Returning'
    ELSE 'Loyal' 
    END as customer_segment
    from customer
    )
select customer_segment, COUNT(*) as 'Number Of Customers'
from customer_type
group by customer_segment ;


-- Q8: what are the top 3 most purchase products within each category ?
with item_counts as(
select category, item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() OVER(PARTITION BY category order by COUNT(customer_id)desc) as item_rank               -- rank Vs dense_rank Vs row_number , because we need 3 different ranks, so i took ROW_NUMBER. similarly [rank and dense_rank] will put sunglasses and belt both as rank 1
from customer
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
WHERE item_rank <= 3 ;

-- Q9: are customer who are repeat buyers (more than 5 previous purchases) also likely to subscribe ? --
select subscription_status,
COUNT(customer_id) as repeat_buyers
from customer
WHERE previous_purchases > 5
group by subscription_status ;

-- Q10: what is the revenue contribution of each age group ? --
select age_group,
SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc ;
